# prod 환경
spring:
  datasource:
    url: jdbc:mariadb://datepickdb.cbwheay2prg8.ap-northeast-2.rds.amazonaws.com:3306/datepickdb_prod
    driver-class-name: org.mariadb.jdbc.Driver
    username: hdjadmin
    password: tlrmsldpf2773
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  redis:
    host: datepick-redis-001.cz4fdc.0001.apn2.cache.amazonaws.com
    port: 6379

# Firebase
firebase:
  account:
    key-path: firebase-config-prod.json
