--- # dev 환경

server:
  port: 8080
spring:
  datasource:
    url: jdbc:mariadb://datepickdb.cbwheay2prg8.ap-northeast-2.rds.amazonaws.com:3306/datepickdb_dev
    driver-class-name: org.mariadb.jdbc.Driver
    username: hdjadmin
    password: tlrmsldpf2773
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true