# Server
server:
  port: 8080
  error:
    include-exception: true
    include-binding-errors: always
    include-message: always
    whitelabel:
      enabled: false

# Spring
spring:
  profiles:
    default: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB       # TODO
      max-request-size: 215MB   # TODO
  jackson:
    property-naming-strategy: SNAKE_CASE
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 1000
  autoconfigure:
    exclude:
      - org.springframework.cloud.aws.autoconfigure.context.ContextInstanceDataAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.context.ContextStackAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.context.ContextRegionProviderAutoConfiguration

# AWS S3
cloud:
  aws:
    credentials:
      access-key: AKIAYWWDOMJ3F57AQYLI
      secret-key: 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
    s3:
      bucket: datepick-storage
    region:
      static: ap-northeast-2
    stack:
      auto: false
    cloudfront:
      host: cdn.datepick.app