# Common 공통 설정
spring.profiles.active: dev   # 환경 선택

server:
  port: 8080
  servlet:
    context-path: /api
  error:
    include-exception: true
    include-binding-errors: always
    include-message: always
    whitelabel:
      enabled: false

--- # local 환경

#spring:
#  config:
#    activate:
#      on-profile: local

--- # dev 환경


spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mariadb://datepickdb.cbwheay2prg8.ap-northeast-2.rds.amazonaws.com:3306/datepick_dummy_db_utf8
    driver-class-name: org.mariadb.jdbc.Driver
    username: hdjadmin
    password: tlrmsldpf2773
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

--- # prod 환경

#spring:
#  profiles:
#    active:
#      on-profile: prod

