# Server
server:
  port: 8080
  error:
    include-exception: true
    include-binding-errors: always
    include-message: always
    whitelabel:
      enabled: false

# Spring
spring:
  profiles:
    default: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB       # TODO
      max-request-size: 215MB   # TODO
  autoconfigure:
    exclude:
      - org.springframework.cloud.aws.autoconfigure.context.ContextInstanceDataAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.context.ContextStackAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.context.ContextRegionProviderAutoConfiguration

# AWS S3
cloud:
  aws:
    credentials:
      access-key: AKIAYWWDOMJ3F57AQYLI
      secret-key: 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
    s3:
      bucket: datepick-storage
    region:
      static: ap-northeast-2
    stack:
      auto: false
    cloudfront:
      host: cdn.datepick.app

# Security
security:
  firebase-props:
    database-url: ${FIREBASE_DATABASE}
    enable-strict-server-session: false
    enable-check-session-revoked: false
    enable-logout-everywhere: false
    session-expiry-in-days: 5
  cookie-props:
    max-age-in-minutes: 7200
    http-only: true
    secure: true
    domain: ${DOMAIN}
    path: /
  allow-credentials: true
  allowed-origins:
    - https://${DOMAIN}
    - http://localhost:8080
  allowed-methods:
    - GET
    - POST
    - PATCH
    - DELETE
  allowed-headers:
    - Authorization
    - Origin
    - Content-Type
    - Accept
    - Accept-Encoding
    - Accept-Language
    - Access-Control-Allow-Origin
    - Access-Control-Allow-Headers
    - Access-Control-Request-Method
    - X-Requested-With
    - X-Auth-Token
    - X-Xsrf-Token
    - Cache-Control
    - Id-Token
  exposed-headers:
    - X-Xsrf-Token